GET http://localhost:3000/

###

GET http://localhost:3000/62b5937d4a7d5230f9b26570

###

POST http://localhost:3000/
Content-Type: application/json

{
    "title": "Eragon 2",
    "note": 4,
    "image": "url_link"
}

###

DELETE http://localhost:3000/62b5b10a1453ca17ea48104c

###

PATCH http://localhost:3000/62b5b10a1453ca17ea48104c
Content-Type: application/json

{
    "title": "Eragon 2",
    "note": 4,
    "image": "url_link_modified"
}